### ISSUE TITLE
老大，v4求指导

### ISSUE THREAD

**Issue by sofs2005** [chiupam/JD_Diy#28]
被我折腾了几次v4的bot起不来了
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/jd/jbot/__init__.py", line 72, in <module>
    jdbot = TelegramClient('bot', api_id, api_hash,
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 529, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest)

网上说只要把telthon的session文件删掉就可以了，不过我找来找去找不到session文件在哪里，还有救不？不行只能重新拉镜像了重新部署了

**Comment by chiupam** [comment]
在你的容器根目录
